### ISSUE TITLE
catpy on pypi

### ISSUE THREAD

**Issue by unidesigner** [catmaid/catpy#18]
Would it be possible to create a catpy release on PyPi? Thanks.

**Comment by aschampion** [comment]
@clbarnes I think it'd make sense for you to own this package since you're the main author. If you have time today we can try to get the autorelease process from diluvian working with this.

**Comment by clbarnes** [comment]
Sure. I have a template for version bumping and deploying too (although I can't remember which of my projects it actually works on...), so I'd be interested to compare.

**Comment by clbarnes** [comment]
https://pypi.org/project/catpy/
